-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agendamento_notificacoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  agendamento_id uuid,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['email'::character varying, 'sms'::character varying, 'push'::character varying, 'in_app'::character varying]::text[])),
  titulo character varying NOT NULL,
  mensagem text NOT NULL,
  lida boolean DEFAULT false,
  enviada_em timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  data_envio timestamp with time zone,
  CONSTRAINT agendamento_notificacoes_pkey PRIMARY KEY (id),
  CONSTRAINT agendamento_notificacoes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id),
  CONSTRAINT agendamento_notificacoes_agendamento_id_fkey FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos(id)
);
CREATE TABLE public.agendamentos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paciente_id uuid,
  clinica_id uuid NOT NULL,
  profissional_id uuid,
  data_hora timestamp with time zone NOT NULL,
  tipo_consulta character varying NOT NULL DEFAULT 'consulta_geral'::character varying,
  status character varying DEFAULT 'pendente'::character varying CHECK (status::text = ANY (ARRAY['pendente'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'concluido'::character varying]::text[])),
  observacoes text,
  codigo_confirmacao character varying UNIQUE,
  valor numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paciente_dados_id uuid,
  servico_id uuid,
  tipo_agendamento character varying DEFAULT 'paciente'::character varying CHECK (tipo_agendamento::text = ANY (ARRAY['paciente'::character varying, 'interno'::character varying]::text[])),
  external_id text,
  booking_source text DEFAULT 'internal'::text CHECK (booking_source = ANY (ARRAY['internal'::text, 'external'::text])),
  chat_session_id uuid,
  dados_coletados_chat jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT agendamentos_pkey PRIMARY KEY (id),
  CONSTRAINT agendamentos_servico_id_fkey FOREIGN KEY (servico_id) REFERENCES public.servicos(id),
  CONSTRAINT agendamentos_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.clinic_professionals(id),
  CONSTRAINT agendamentos_chat_session_id_fkey FOREIGN KEY (chat_session_id) REFERENCES public.chat_sessions(id),
  CONSTRAINT agendamentos_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES auth.users(id),
  CONSTRAINT agendamentos_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinics(id),
  CONSTRAINT agendamentos_paciente_dados_id_fkey FOREIGN KEY (paciente_dados_id) REFERENCES public.pacientes(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  professional_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  treatment_id uuid,
  scheduled_date timestamp with time zone NOT NULL,
  duration_minutes integer DEFAULT 60,
  status USER-DEFINED DEFAULT 'scheduled'::appointment_status,
  notes text,
  price numeric,
  payment_status USER-DEFINED DEFAULT 'pending'::payment_status,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_appointments_professional FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT fk_appointments_clinic FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT fk_appointments_treatment FOREIGN KEY (treatment_id) REFERENCES public.treatments(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action character varying NOT NULL,
  table_name character varying,
  record_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.chat_booking_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid,
  user_id uuid,
  specialty_id uuid,
  clinic_id uuid,
  service_id uuid,
  selected_date date,
  selected_time time without time zone,
  patient_data jsonb DEFAULT '{}'::jsonb,
  booking_step character varying DEFAULT 'selecting_specialty'::character varying,
  status character varying DEFAULT 'in_progress'::character varying CHECK (status::text = ANY (ARRAY['in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_booking_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT chat_booking_sessions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id),
  CONSTRAINT chat_booking_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT chat_booking_sessions_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.chat_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'abandoned'::text])),
  current_step text DEFAULT 'greeting'::text CHECK (current_step = ANY (ARRAY['greeting'::text, 'clinic_selection'::text, 'service_selection'::text, 'date_selection'::text, 'time_selection'::text, 'patient_info'::text, 'confirmation'::text, 'completed'::text])),
  selected_clinic_id uuid,
  selected_service_id uuid,
  selected_date date,
  selected_time time without time zone,
  patient_name text,
  patient_phone text,
  patient_email text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chat_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT chat_conversations_selected_clinic_id_fkey FOREIGN KEY (selected_clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT chat_conversations_selected_service_id_fkey FOREIGN KEY (selected_service_id) REFERENCES public.servicos(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid,
  sender character varying CHECK (sender::text = ANY (ARRAY['user'::character varying, 'bot'::character varying, 'system'::character varying]::text[])),
  content text NOT NULL,
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying, 'buttons'::character varying, 'quick_reply'::character varying, 'system'::character varying]::text[])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.chat_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'abandoned'::character varying]::text[])),
  context jsonb DEFAULT '{}'::jsonb,
  current_step character varying DEFAULT 'greeting'::character varying,
  booking_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  session_id character varying,
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT chat_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.clinic_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL UNIQUE,
  subscriber_id text NOT NULL,
  api_token_encrypted bytea NOT NULL,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinic_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_credentials_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.clinic_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  clinic_name text,
  api_user text NOT NULL,
  api_token text NOT NULL,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  online_slug text,
  provider text,
  CONSTRAINT clinic_integrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clinic_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  email character varying NOT NULL,
  telefone character varying NOT NULL,
  nome_clinica character varying NOT NULL,
  especialidade character varying NOT NULL,
  cidade character varying NOT NULL,
  mensagem text,
  status character varying DEFAULT 'novo'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  razao_social character varying,
  cnpj character varying,
  nome_fantasia character varying,
  cro_responsavel character varying,
  carteirinha_cro_url character varying,
  instagram character varying,
  site character varying,
  uf character varying,
  bairro character varying,
  numero_cadeiras integer,
  orcamentos_mes integer,
  ticket_medio numeric,
  faturamento_mensal numeric,
  local_clinica character varying,
  tem_credito boolean DEFAULT false,
  valor_credito numeric,
  banco_credito character varying,
  tem_outros_servicos boolean DEFAULT false,
  outros_servicos text,
  cargo character varying,
  como_conheceu character varying,
  especialidades ARRAY,
  CONSTRAINT clinic_leads_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clinic_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  loan_request_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info'::text,
  is_read boolean NOT NULL DEFAULT false,
  admin_response_data jsonb,
  parcelamais_response_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clinic_notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clinic_professionals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'dentist'::text CHECK (role = ANY (ARRAY['dentist'::text, 'assistant'::text, 'receptionist'::text, 'manager'::text])),
  permissions jsonb DEFAULT '{"access_agenda": true, "access_reports": false, "access_patients": false, "access_financial": false, "access_advanced_services": false}'::jsonb,
  is_active boolean DEFAULT true,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinic_professionals_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_professionals_user_id_profiles_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT clinic_professionals_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT clinic_professionals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT clinic_professionals_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.clinic_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL UNIQUE,
  logo_url text,
  cover_image_url text,
  description text,
  specialties ARRAY DEFAULT '{}'::text[],
  team_size integer DEFAULT 0,
  founded_year integer,
  certifications ARRAY DEFAULT '{}'::text[],
  insurance_accepted ARRAY DEFAULT '{}'::text[],
  gallery_images ARRAY DEFAULT '{}'::text[],
  languages_spoken ARRAY DEFAULT '{}'::text[],
  working_hours jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinic_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_profiles_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.clinic_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  service_name text NOT NULL,
  service_description text,
  price numeric,
  duration_minutes integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinic_services_pkey PRIMARY KEY (id),
  CONSTRAINT clinic_services_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.clinicorp_appointments (
  id bigint NOT NULL DEFAULT nextval('clinicorp_appointments_id_seq'::regclass),
  clinic_id uuid,
  clinicorp_appointment_id text NOT NULL,
  patient_id uuid,
  professional_id text,
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'scheduled'::text,
  meta jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clinicorp_appointments_pkey PRIMARY KEY (id),
  CONSTRAINT clinicorp_appointments_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT clinicorp_appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES auth.users(id)
);
CREATE TABLE public.clinicorp_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  default_api_user text NOT NULL,
  default_api_token text NOT NULL,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  api_key text,
  subscriber_id text,
  base_url text,
  user_id uuid,
  is_active boolean DEFAULT true,
  CONSTRAINT clinicorp_credentials_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clinics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  cnpj text UNIQUE,
  email text UNIQUE,
  phone text,
  address jsonb,
  description text,
  logo_url text,
  website text,
  social_media jsonb,
  operating_hours jsonb,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  rating numeric DEFAULT 0.00,
  total_reviews integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  subscription_plan character varying DEFAULT 'basic'::character varying CHECK (subscription_plan::text = ANY (ARRAY['basic'::character varying, 'essential'::character varying, 'advanced'::character varying]::text[])),
  services_config jsonb DEFAULT '{"advanced": [], "essential": []}'::jsonb,
  master_user_id uuid,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying]::text[])),
  clinic_slug text UNIQUE,
  hero_image_url text,
  whatsapp_url text,
  clinicorp_enabled boolean DEFAULT false,
  clinicorp_api_user text,
  clinicorp_api_token bytea,
  clinicorp_subscriber_id text,
  clinicorp_business_id_default text,
  clinicorp_code_link_default text,
  clinicorp_webhook_secret bytea,
  clinicorp_base_url text DEFAULT 'https://api.clinicorp.com/rest/v1'::text,
  city text,
  agenda_link_url text,
  owner_id uuid,
  doutorizze_api_url text,
  doutorizze_api_token text,
  doutorizze_enabled boolean DEFAULT false,
  CONSTRAINT clinics_pkey PRIMARY KEY (id),
  CONSTRAINT clinics_master_user_id_fkey FOREIGN KEY (master_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.credit_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  credit_request_id uuid NOT NULL,
  document_type character varying NOT NULL,
  document_name character varying NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  mime_type character varying,
  uploaded_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'pending'::character varying,
  verified_at timestamp with time zone,
  verified_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credit_documents_pkey PRIMARY KEY (id),
  CONSTRAINT credit_documents_credit_request_id_fkey FOREIGN KEY (credit_request_id) REFERENCES public.credit_requests(id),
  CONSTRAINT credit_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id)
);
CREATE TABLE public.credit_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  credit_request_id uuid NOT NULL,
  bank_name character varying NOT NULL,
  approved_amount numeric NOT NULL,
  interest_rate numeric NOT NULL,
  installments integer NOT NULL,
  conditions text,
  monthly_payment numeric,
  total_amount numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credit_offers_pkey PRIMARY KEY (id),
  CONSTRAINT credit_offers_credit_request_id_fkey FOREIGN KEY (credit_request_id) REFERENCES public.credit_requests(id)
);
CREATE TABLE public.credit_request_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  credit_request_id uuid,
  field_name character varying NOT NULL,
  old_value text,
  new_value text,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now(),
  change_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credit_request_history_pkey PRIMARY KEY (id),
  CONSTRAINT credit_request_history_credit_request_id_fkey FOREIGN KEY (credit_request_id) REFERENCES public.credit_requests(id),
  CONSTRAINT credit_request_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.credit_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'clinic_approved'::character varying::text, 'clinic_rejected'::character varying::text, 'admin_analyzing'::character varying::text, 'admin_approved'::character varying::text, 'admin_rejected'::character varying::text, 'approved'::character varying::text, 'rejected'::character varying::text, 'cancelled'::character varying::text])),
  description text,
  patient_name character varying NOT NULL,
  patient_email character varying NOT NULL,
  patient_phone character varying,
  patient_cpf character varying,
  treatment_type character varying,
  urgency_level character varying DEFAULT 'normal'::character varying CHECK (urgency_level::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  requested_date date,
  clinic_notes text,
  admin_notes text,
  approved_at timestamp with time zone,
  approved_by uuid,
  rejected_at timestamp with time zone,
  rejected_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  installments integer DEFAULT 1 CHECK (installments > 0 AND installments <= 60),
  requested_amount numeric NOT NULL DEFAULT 0 CHECK (requested_amount > 0::numeric),
  treatment_description text,
  clinic_approved_amount numeric,
  clinic_installments integer,
  clinic_interest_rate numeric DEFAULT 2.5,
  special_conditions text,
  edited_by_clinic boolean DEFAULT false,
  clinic_edit_date timestamp with time zone,
  clinic_comments text,
  admin_comments text,
  analysis_status character varying DEFAULT 'pending'::character varying CHECK (analysis_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'in_analysis'::character varying, 'contracted'::character varying, 'disbursed'::character varying]::text[])),
  analyzed_at timestamp with time zone,
  analyzed_by uuid,
  CONSTRAINT credit_requests_pkey PRIMARY KEY (id),
  CONSTRAINT credit_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT credit_requests_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES auth.users(id),
  CONSTRAINT credit_requests_analyzed_by_fkey FOREIGN KEY (analyzed_by) REFERENCES auth.users(id),
  CONSTRAINT credit_requests_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT credit_requests_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.credit_simulations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  amount numeric NOT NULL,
  installments integer NOT NULL,
  interest_rate numeric NOT NULL,
  total_amount numeric NOT NULL,
  installment_value numeric NOT NULL,
  is_pre_approved boolean DEFAULT false,
  simulation_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credit_simulations_pkey PRIMARY KEY (id),
  CONSTRAINT credit_simulations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.edit_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  credit_request_id uuid,
  clinic_id uuid,
  draft_amount numeric,
  draft_installments integer,
  draft_rate numeric,
  draft_notes text,
  draft_conditions text,
  saved_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT edit_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT edit_drafts_credit_request_id_fkey FOREIGN KEY (credit_request_id) REFERENCES public.credit_requests(id),
  CONSTRAINT edit_drafts_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.error_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text,
  error_type text NOT NULL,
  error_message text NOT NULL,
  error_details jsonb,
  function_name text NOT NULL,
  stack_trace text,
  user_agent text,
  ip_address inet,
  created_at timestamp with time zone DEFAULT now(),
  resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  CONSTRAINT error_logs_pkey PRIMARY KEY (id),
  CONSTRAINT error_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT error_logs_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.faq_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  categoria character varying NOT NULL,
  pergunta text NOT NULL,
  resposta text NOT NULL,
  keywords ARRAY,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT faq_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  professional_id uuid,
  clinic_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT fk_favorites_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_favorites_professional FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT fk_favorites_clinic FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.horarios_bloqueados (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinica_id uuid NOT NULL,
  profissional_id uuid,
  data_inicio timestamp with time zone NOT NULL,
  data_fim timestamp with time zone NOT NULL,
  motivo character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT horarios_bloqueados_pkey PRIMARY KEY (id),
  CONSTRAINT horarios_bloqueados_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.clinic_professionals(id),
  CONSTRAINT horarios_bloqueados_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.horarios_funcionamento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinica_id uuid NOT NULL,
  dia_semana integer NOT NULL CHECK (dia_semana >= 0 AND dia_semana <= 6),
  hora_inicio time without time zone NOT NULL,
  hora_fim time without time zone NOT NULL,
  duracao_consulta integer DEFAULT 30,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT horarios_funcionamento_pkey PRIMARY KEY (id),
  CONSTRAINT horarios_funcionamento_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.loan_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  clinic_id uuid NOT NULL,
  treatment_id uuid,
  requested_amount numeric NOT NULL,
  approved_amount numeric,
  interest_rate numeric,
  installments integer,
  status USER-DEFINED DEFAULT 'pending'::loan_status,
  documents jsonb,
  credit_score integer,
  approval_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  final_decision_details jsonb,
  admin_decision_date timestamp with time zone,
  parcelamais_final_status text,
  notification_sent_at timestamp with time zone,
  CONSTRAINT loan_requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_loan_requests_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_loan_requests_clinic FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT fk_loan_requests_treatment FOREIGN KEY (treatment_id) REFERENCES public.treatments(id)
);
CREATE TABLE public.loan_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key character varying NOT NULL UNIQUE,
  setting_value numeric NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loan_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loyalty_points (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  points integer NOT NULL DEFAULT 0,
  action_type character varying NOT NULL,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  earned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_points_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  appointment_id uuid,
  subject text,
  content text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_messages_recipient FOREIGN KEY (recipient_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_messages_appointment FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.notificacoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  titulo character varying NOT NULL,
  mensagem text NOT NULL,
  tipo character varying DEFAULT 'info'::character varying CHECK (tipo::text = ANY (ARRAY['info'::character varying, 'success'::character varying, 'warning'::character varying, 'error'::character varying]::text[])),
  lida boolean DEFAULT false,
  data_criacao timestamp with time zone DEFAULT now(),
  data_leitura timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notificacoes_pkey PRIMARY KEY (id),
  CONSTRAINT notificacoes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type USER-DEFINED DEFAULT 'info'::notification_type,
  is_read boolean DEFAULT false,
  action_url text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.pacientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  telefone character varying NOT NULL,
  email character varying,
  data_nascimento date,
  cpf character varying,
  endereco jsonb,
  observacoes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pacientes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  medical_history jsonb,
  allergies ARRAY,
  medications ARRAY,
  emergency_contact jsonb,
  insurance_info jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patients_pkey PRIMARY KEY (id),
  CONSTRAINT fk_patients_profile FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payment_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  stripe_customer_id text,
  stripe_payment_intent_id text NOT NULL UNIQUE,
  stripe_invoice_id text,
  subscription_id uuid,
  amount integer NOT NULL,
  currency text NOT NULL DEFAULT 'brl'::text,
  status text NOT NULL,
  payment_method_type text,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_history_pkey PRIMARY KEY (id),
  CONSTRAINT payment_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payment_history_stripe_customer_id_fkey FOREIGN KEY (stripe_customer_id) REFERENCES public.stripe_customers(stripe_customer_id),
  CONSTRAINT payment_history_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid,
  patient_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_method text,
  status USER-DEFINED DEFAULT 'pending'::payment_status,
  transaction_id text,
  gateway_response jsonb,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payments_appointment FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT fk_payments_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.preventive_care_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  task_type character varying NOT NULL,
  title character varying NOT NULL,
  description text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'skipped'::character varying]::text[])),
  points_earned integer DEFAULT 0,
  due_date date,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT preventive_care_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT preventive_care_tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pricing_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  price numeric NOT NULL,
  period character varying NOT NULL DEFAULT 'mensal'::character varying,
  description text,
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_popular boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  plan_type text NOT NULL DEFAULT 'clinic'::text CHECK (plan_type = ANY (ARRAY['patient'::text, 'clinic'::text, 'clinic_advanced'::text])),
  CONSTRAINT pricing_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.professionals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  clinic_id uuid,
  license_number text UNIQUE,
  specialties ARRAY,
  bio text,
  experience_years integer,
  consultation_fee numeric,
  is_available boolean DEFAULT true,
  rating numeric DEFAULT 0.00,
  total_reviews integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professionals_pkey PRIMARY KEY (id),
  CONSTRAINT fk_professionals_profile FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_professionals_clinic FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  user_id uuid NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  full_name text,
  role USER-DEFINED NOT NULL DEFAULT 'patient'::user_role,
  avatar_url text,
  phone text,
  cpf text UNIQUE,
  birth_date date,
  gender text,
  address jsonb,
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  phone_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  account_type text NOT NULL CHECK (account_type = ANY (ARRAY['paciente'::text, 'clinica'::text])),
  rg character varying,
  marital_status character varying CHECK (marital_status::text = ANY (ARRAY['solteiro'::character varying, 'casado'::character varying, 'divorciado'::character varying, 'viuvo'::character varying, 'uniao_estavel'::character varying]::text[])),
  profession character varying,
  monthly_income numeric,
  bank_name character varying,
  bank_code character varying,
  bank_agency character varying,
  bank_account character varying,
  bank_account_type character varying CHECK (bank_account_type::text = ANY (ARRAY['corrente'::character varying, 'poupanca'::character varying]::text[])),
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  professional_id uuid,
  clinic_id uuid,
  appointment_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  is_anonymous boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT fk_reviews_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_reviews_professional FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT fk_reviews_clinic FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT fk_reviews_appointment FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.security_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action character varying NOT NULL,
  resource character varying,
  ip_address inet,
  user_agent text,
  status character varying DEFAULT 'success'::character varying CHECK (status::text = ANY (ARRAY['success'::character varying, 'failed'::character varying, 'blocked'::character varying]::text[])),
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT security_logs_pkey PRIMARY KEY (id),
  CONSTRAINT security_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.servicos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  nome character varying NOT NULL,
  descricao text,
  duracao_minutos integer NOT NULL DEFAULT 30,
  preco numeric,
  ativo boolean DEFAULT true,
  categoria character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT servicos_pkey PRIMARY KEY (id),
  CONSTRAINT servicos_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.site_configurations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_key text NOT NULL UNIQUE,
  config_value jsonb NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT site_configurations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL UNIQUE,
  value text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.specialties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  icon text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT specialties_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stripe_customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  stripe_customer_id text NOT NULL UNIQUE,
  email text NOT NULL,
  name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_customers_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.stripe_webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_event_id text NOT NULL UNIQUE,
  event_type text NOT NULL,
  processed boolean DEFAULT false,
  data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_webhook_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_plan_benefits (
  id integer NOT NULL DEFAULT nextval('subscription_plan_benefits_id_seq'::regclass),
  plan_id integer,
  benefit_text text NOT NULL,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plan_benefits_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_plan_benefits_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.subscription_plans (
  id integer NOT NULL DEFAULT nextval('subscription_plans_id_seq'::regclass),
  name character varying NOT NULL,
  description text,
  price_monthly numeric NOT NULL,
  price_annual numeric NOT NULL,
  original_price_monthly numeric,
  original_price_annual numeric,
  is_popular boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  stripe_customer_id text,
  stripe_subscription_id text NOT NULL UNIQUE,
  stripe_price_id text NOT NULL,
  stripe_product_id text NOT NULL,
  plan_id text NOT NULL,
  status text NOT NULL,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  canceled_at timestamp with time zone,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT subscriptions_stripe_customer_id_fkey FOREIGN KEY (stripe_customer_id) REFERENCES public.stripe_customers(stripe_customer_id)
);
CREATE TABLE public.support_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  sender_id uuid,
  sender_name character varying NOT NULL,
  sender_type character varying NOT NULL CHECK (sender_type::text = ANY (ARRAY['user'::character varying, 'admin'::character varying]::text[])),
  message text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_messages_pkey PRIMARY KEY (id),
  CONSTRAINT support_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT support_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  clinic_id uuid,
  title character varying NOT NULL,
  description text NOT NULL,
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  category character varying NOT NULL,
  assigned_to uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  admin_response text,
  resolved_by uuid,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT support_tickets_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT support_tickets_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL,
  description text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.testimonials (
  id integer NOT NULL DEFAULT nextval('testimonials_id_seq'::regclass),
  name character varying NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text NOT NULL,
  treatment character varying,
  clinic character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT testimonials_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ticket_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid,
  sender_id uuid,
  message text NOT NULL,
  is_admin_reply boolean DEFAULT false,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ticket_messages_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT ticket_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id)
);
CREATE TABLE public.treatments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  specialty_id uuid,
  duration_minutes integer,
  base_price numeric,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT treatments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_treatments_specialty FOREIGN KEY (specialty_id) REFERENCES public.specialties(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  name character varying NOT NULL,
  user_type character varying DEFAULT 'patient'::character varying CHECK (user_type::text = ANY (ARRAY['patient'::character varying, 'clinic_staff'::character varying, 'clinic_master'::character varying, 'admin'::character varying]::text[])),
  avatar_url text,
  phone character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.webhook_events (
  id bigint NOT NULL DEFAULT nextval('webhook_events_id_seq'::regclass),
  clinic_id uuid,
  event_id text NOT NULL,
  event_type text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb,
  received_at timestamp with time zone DEFAULT now(),
  CONSTRAINT webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_events_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.workflow_flows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  flow_type character varying NOT NULL,
  step_number integer NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  icon_name character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_flows_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workflow_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text NOT NULL,
  icon_name character varying NOT NULL,
  step_number integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_steps_pkey PRIMARY KEY (id)
);