-- Create 3 demo clinics with valid UUIDs
INSERT INTO public.clinics (
  name, 
  description, 
  address, 
  city, 
  state, 
  zip_code, 
  phone, 
  email, 
  rating, 
  total_reviews,
  latitude,
  longitude,
  website,
  is_active
) VALUES 
(
  'Clínica Dental doltorizze Plus',
  'Especializada em odontologia estética e implantes dentários. Oferecemos tratamentos modernos com tecnologia de ponta.',
  'Rua das Flores, 123',
  'São Paulo',
  'SP',
  '01234-567',
  '(11) 99999-0001',
  'contato@doltorizzeplus.com.br',
  4.8,
  127,
  -23.5505,
  -46.6333,
  'https://doltorizzeplus.com.br',
  true
),
(
  'OdontoExcelência Centro',
  'Clínica completa com especialistas em ortodontia, endodontia e cirurgia oral. Atendimento humanizado e de qualidade.',
  'Av. Paulista, 456',
  'São Paulo',
  'SP',
  '01310-100',
  '(11) 99999-0002',
  'atendimento@odontoexcelencia.com.br',
  4.6,
  203,
  -23.5616,
  -46.6562,
  'https://odontoexcelencia.com.br',
  true
),
(
  'Dental Care Premium',
  'Referência em tratamentos odontológicos premium. Oferecemos desde limpeza até procedimentos complexos de reabilitação oral.',
  'Rua Augusta, 789',
  'São Paulo',
  'SP',
  '01305-000',
  '(11) 99999-0003',
  'premium@dentalcare.com.br',
  4.9,
  156,
  -23.5489,
  -46.6511,
  'https://dentalcarepremium.com.br',
  true
);